spring:
  redis:
    host: 43.136.110.115
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.125.16:3306/foodRecomment?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: tuijian123456
    hikari:
      idle-timeout: 10000
      max-lifetime: 30000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  设置时区，不然前端查出来时间慢八小时
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置文件上传的属性
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  boot版本太高，为了swagger不报错用这个

#mybatis:
#  mapper-locations: classpath:mappers/*Mapper.xml
#  type-aliases-package: com.example.foodrecommend.beans


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.foodrecommend.beans
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 8080


qiNiuYun:
  link: http://s4803lpy1.hd-bkt.clouddn.com/


